name: Linting and formatting on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Performs linting, formatting on the application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies (Ignore Postinstall)
        run: npm install
        env:
          npm_config_ignore_scripts: true

      - name: Generate prisma client
        run: npm run db:prisma

      - name: Run Build
        run: npm run build
